#!/bin/bash

PYTHON_INSPECTOR_INDEX_URL="https://jfrog.hub.vwgroup.com/artifactory/api/pypi/optima-pypi-virtual/simple"
export PYTHON_INSPECTOR_INDEX_URL

temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/myprefix.XXXXXX")

echo "Temp dir used: $temp_dir"

poetry export \
    --without-hashes \
    --without-urls \
    --format=requirements.txt \
    --only=main > "$temp_dir/requirements.txt"

python-inspector \
    --python-version 311 \
    --operating-system linux \
    --json-pdt "$temp_dir/python_inspector_pdt.json" \
    --analyze-setup-py-insecurely \
    --requirement "$temp_dir/requirements.txt"  "$@"
